import { useState } from 'react';
import { ServerIcon, ChartPieIcon, CurrencyEuroIcon, ShieldCheckIcon, InformationCircleIcon, XMarkIcon } from '@heroicons/react/24/outline';
import { formatCurrency, formatPercentage } from '@/lib/solana/calculateMetrics';

interface KPICardsProps {
    ovhNodes: number;
    marketShare: number;
    estimatedRevenue: number;
    stakeShare?: number; // New prop
}

export default function KPICards({ ovhNodes, marketShare, estimatedRevenue, stakeShare }: KPICardsProps) {
    const [activeTooltip, setActiveTooltip] = useState<number | null>(null);

    const cards = [
        {
            title: 'Active OVH Nodes',
            value: ovhNodes.toString(),
            icon: ServerIcon,
            color: 'cyan',
            gradient: 'from-[#00F0FF]/20 via-[#6B4FBB]/10 to-transparent',
            tooltipTitle: 'Active OVH Nodes',
            tooltipContent: 'Total number of Solana voting validators currently identifying as hosting on OVHcloud infrastructure via their ASN (Autonomous System Number). Detected using MaxMind GeoLite2 ASN database mapping.'
        },
        {
            title: 'Market Share (Nodes)',
            value: formatPercentage(marketShare),
            icon: ChartPieIcon,
            color: 'purple',
            gradient: 'from-[#6B4FBB]/20 via-[#00F0FF]/10 to-transparent',
            tooltipTitle: 'Node Market Share',
            tooltipContent: 'Percentage of total network nodes hosted on OVH. Calculated as: (OVH Nodes / Total Active Validators) * 100.'
        },
        {
            title: 'Network Security (Stake)',
            value: stakeShare !== undefined ? formatPercentage(stakeShare) : 'Loading...',
            icon: ShieldCheckIcon,
            color: 'green',
            gradient: 'from-emerald-500/20 via-teal-500/10 to-transparent',
            tooltipTitle: 'Stake Weight (Security %)',
            tooltipContent: 'Percentage of total network active stake (SOL) delegated to OVH nodes. This represents the actual voting power and security influence of OVH on the network.'
        },
        {
            title: 'Est. Monthly Revenue',
            value: formatCurrency(estimatedRevenue),
            icon: CurrencyEuroIcon,
            color: 'cyan',
            gradient: 'from-[#00F0FF]/20 via-[#00296B]/10 to-transparent',
            tooltipTitle: 'Estimated Revenue',
            tooltipContent: 'Estimated monthly revenue generated by OVHcloud from these validators. Based on a conservative estimate of €150/month per dedicated server instance.'
        },
    ];

    return (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6">
            {cards.map((card, index) => (
                <div
                    key={index}
                    onClick={() => setActiveTooltip(index)}
                    className="group relative overflow-hidden rounded-2xl glass-card hover:border-[#00F0FF]/50 transition-all duration-300 hover:scale-[1.02] cursor-pointer"
                >
                    {/* Gradient overlay */}
                    <div className={`absolute inset-0 bg-gradient-to-br ${card.gradient} opacity-50 group-hover:opacity-100 transition-opacity duration-500`}></div>

                    <div className="relative p-6 z-10">
                        {/* Info Icon Helper */}
                        <div className="absolute top-4 right-4 text-white/20 group-hover:text-[#00F0FF] transition-colors">
                            <InformationCircleIcon className="w-5 h-5" />
                        </div>

                        <div className="flex flex-col h-full justify-between">
                            <div>
                                <p className="text-xs font-bold text-gray-400 mb-2 uppercase tracking-wider">{card.title}</p>
                                <p className={`text-3xl font-black ${card.color === 'cyan' ? 'text-[#00F0FF]' :
                                    card.color === 'purple' ? 'text-[#6B4FBB]' : 'text-emerald-400'
                                    } drop-shadow-lg truncate`}>
                                    {card.value}
                                </p>
                            </div>

                            <div className="mt-4 flex justify-end">
                                <div className={`p-2 rounded-lg bg-white/5 border border-white/10 group-hover:scale-110 transition-transform duration-300`}>
                                    <card.icon className={`w-6 h-6 ${card.color === 'cyan' ? 'text-[#00F0FF]' :
                                        card.color === 'purple' ? 'text-[#6B4FBB]' : 'text-emerald-400'
                                        }`} />
                                </div>
                            </div>
                        </div>

                        {/* Animated bottom border */}
                        <div className="absolute bottom-0 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-[#00F0FF] to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
                    </div>

                    {/* Tooltip Overlay (Click activated) */}
                    {activeTooltip === index && (
                        <div
                            className="absolute inset-0 z-50 bg-[#050510]/95 backdrop-blur-md p-6 flex flex-col justify-center animate-fade-in"
                            onClick={(e) => {
                                e.stopPropagation();
                                setActiveTooltip(null);
                            }}
                        >
                            <button className="absolute top-4 right-4 text-white/50 hover:text-white">
                                <XMarkIcon className="w-5 h-5" />
                            </button>
                            <h4 className="text-[#00F0FF] font-bold mb-2">{card.tooltipTitle}</h4>
                            <p className="text-sm text-gray-300 leading-relaxed">
                                {card.tooltipContent}
                            </p>
                            <span className="text-xs text-white/30 mt-4 text-center">Click to close</span>
                        </div>
                    )}
                </div>
            ))}
        </div>
    );
}
